// packages/web-components/src/components/loading/loading.ts
/**
 * Copyright IBM Corp. 2019, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import { LOADING_TYPE } from './defs';
import getLoadingIcon from './loading-icon';
import styles from './loading.scss?lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Spinner indicating loading state.
 *
 * @element cds-loading
 */

@customElement(`${prefix}-loading`)
class CDSLoading extends LitElement {
  /**
   * @deprecated
   * The 'assistive-text' property will be deprecated in the next major release. Please use `description` instead.
   */
  @property({ attribute: 'assistive-text' })
  get assistiveText() {
    return this.description;
  }
  set assistiveText(value) {
    this.description = value;
  }

  /**
   * Specify a description that would be used to best describe the loading state
   */
  @property({ reflect: true })
  description = 'Loading';

  /**
   *
   * @deprecated The 'type' property will be deprecated in the next major release. Please use `small` instead.
   */
  @property()
  get type() {
    return this.small ? LOADING_TYPE.SMALL : LOADING_TYPE.REGULAR;
  }
  set type(value) {
    this.small = value === LOADING_TYPE.SMALL;
  }

  /**
   * Specify whether you would like the small variant of <Loading>
   */
  @property({ type: Boolean, reflect: true })
  small = false;

  /**
   * `true` if overlay should be applied.
   */
  @property({ type: Boolean, reflect: true })
  overlay = false;

  /**
   *
   * @deprecated
   * The 'inactive' property will be deprecated in the next major release. Please use `active` instead.
   */
  @property({ type: Boolean, reflect: true })
  get inactive(): boolean {
    return !this.active;
  }

  set inactive(value: boolean) {
    this.active = !value;
  }

  /**
   * Specify whether you want the loading indicator to be spinning or not
   */
  @property({ type: Boolean, reflect: true })
  active = false;

  render() {
    const { active, description, small, overlay } = this;

    const innerClasses = classMap({
      [`${prefix}--loading`]: true,
      [`${prefix}--loading--stop`]: !active,
      [`${prefix}--loading--small`]: small,
    });
    const icon = getLoadingIcon({ description, small });
    return overlay ? html`<div class="${innerClasses}">${icon}</div>` : icon;
  }

  static styles = styles;
}

export { LOADING_TYPE };

export default CDSLoading;

// packages/react/src/components/Loading/Loading.tsx
/**
 * Copyright IBM Corp. 2016, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import PropTypes from 'prop-types';
import React, { type HTMLAttributes } from 'react';
import { usePrefix } from '@carbon/utilities-react';
import { deprecate } from '../../prop-types/deprecate';

export interface LoadingProps extends HTMLAttributes<HTMLDivElement> {
  /**
   * Specify whether you want the loading indicator to be spinning or not
   */
  active?: boolean;

  /**
   * Provide an optional className to be applied to the containing node
   */
  className?: string;

  /**
   * Specify a description that would be used to best describe the loading state
   */
  description?: string;

  /**
   * @deprecated The prop `id` is no longer needed
   */
  id?: string;

  /**
   * Specify whether you would like the small variant of <Loading>
   */
  small?: boolean;

  /**
   * Specify whether you want the loader to be applied with an overlay
   */
  withOverlay?: boolean;
}

function Loading({
  active = true,
  className: customClassName,
  withOverlay = true,
  small = false,
  description = 'loading',
  ...rest
}: LoadingProps) {
  const prefix = usePrefix();
  const loadingClassName = cx(customClassName, {
    [`${prefix}--loading`]: true,
    [`${prefix}--loading--small`]: small,
    [`${prefix}--loading--stop`]: !active,
  });
  const overlayClassName = cx({
    [`${prefix}--loading-overlay`]: true,
    [`${prefix}--loading-overlay--stop`]: !active,
  });

  const loading = (
    <div
      {...rest}
      aria-atomic="true"
      aria-live={active ? 'assertive' : 'off'}
      className={loadingClassName}>
      <svg className={`${prefix}--loading__svg`} viewBox="0 0 100 100">
        <title>{description}</title>
        {small ? (
          <circle
            className={`${prefix}--loading__background`}
            cx="50%"
            cy="50%"
            r="42"
          />
        ) : null}
        <circle
          className={`${prefix}--loading__stroke`}
          cx="50%"
          cy="50%"
          r={small ? '42' : '44'}
        />
      </svg>
    </div>
  );

  return withOverlay ? (
    <div className={overlayClassName}>{loading}</div>
  ) : (
    loading
  );
}

Loading.propTypes = {
  /**
   * Specify whether you want the loading indicator to be spinning or not
   */
  active: PropTypes.bool,

  /**
   * Provide an optional className to be applied to the containing node
   */
  className: PropTypes.string,

  /**
   * Specify a description that would be used to best describe the loading state
   */
  description: PropTypes.string,

  /**
   * Provide an `id` to uniquely identify the label
   */
  id: deprecate(PropTypes.string, `\nThe prop \`id\` is no longer needed.`),

  /**
   * Specify whether you would like the small variant of <Loading>
   */
  small: PropTypes.bool,

  /**
   * Specify whether you want the loader to be applied with an overlay
   */
  withOverlay: PropTypes.bool,
};

export default Loading;
