// packages/web-components/src/components/checkbox/checkbox.ts
/**
 * Copyright IBM Corp. 2019, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { LitElement, html } from 'lit';
import { property, query } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import FormMixin from '../../globals/mixins/form';
import styles from './checkbox.scss?lit';
import WarningFilled16 from '@carbon/icons/es/warning--filled/16.js';
import WarningAltFilled16 from '@carbon/icons/es/warning--alt--filled/16.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { iconLoader } from '../../globals/internal/icon-loader';

/**
 * Check box.
 *
 * @element cds-checkbox
 * @fires cds-checkbox-changed - The custom event fired after this changebox changes its checked state.
 * @csspart input The checkbox.
 * @csspart label The label.
 */
@customElement(`${prefix}-checkbox`)
class CDSCheckbox extends FocusMixin(FormMixin(LitElement)) {
  @query('input')
  protected _checkboxNode!: HTMLInputElement;

  /**
   * Handles `click` event on the `<input>` in the shadow DOM.
   */
  protected _handleChange() {
    const { checked, indeterminate } = this._checkboxNode;
    this.checked = checked;
    this.indeterminate = indeterminate;
    const { eventChange } = this.constructor as typeof CDSCheckbox;
    this.dispatchEvent(
      new CustomEvent(eventChange, {
        bubbles: true,
        composed: true,
        detail: {
          checked,
          indeterminate,
        },
      })
    );
  }

  /**
   * Prevent checkbox state from updating when readonly
   */
  private _handleClick(event: MouseEvent) {
    if (this.readonly) {
      event.preventDefault();
    }
  }

  _handleFormdata(event: FormDataEvent) {
    const { formData } = event;
    const { checked, disabled, name, value = 'on' } = this;
    if (!disabled && checked) {
      formData.append(name, value);
    }
  }

  /**
   * Specify whether the underlying input should be checked
   */
  @property({ type: Boolean, reflect: true, attribute: 'checked' })
  checked = false;

  /**
   * Specify if checkbox is being used in a data table
   */
  @property({ type: Boolean, reflect: true, attribute: 'data-table' })
  dataTable = false;

  /**
   * Specify whether the Checkbox should be disabled
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /**
   * Provide text for the form group for additional help
   */
  @property({ type: String, reflect: true, attribute: 'helper-text' })
  helperText;

  /**
   * Specify whether the checkbox should be present in the DOM,
   * but invisible and uninteractable. Used for data-table purposes.
   */
  @property({ type: Boolean, reflect: true, attribute: 'hide-checkbox' })
  hideCheckbox = false;

  /**
   * Specify whether the label should be hidden, or not
   */
  @property({ type: Boolean, reflect: true, attribute: 'hide-label' })
  hideLabel = false;

  /**
   * Specify a custom id for the checkbox
   */
  @property({ reflect: true })
  id = 'checkbox';

  /**
   * Specify whether the Checkbox is in an indeterminate state
   */
  @property({ type: Boolean, reflect: true })
  indeterminate = false;

  /**
   * Provide a label to provide a description of the Checkbox input that you are
   * exposing to the user
   */
  @property({ attribute: 'label-text' })
  labelText = '';

  /**
   * The form name.
   */
  @property()
  name!: string;

  /**
   * Specify whether the Checkbox is read-only
   */
  @property({ type: Boolean, reflect: true })
  readonly = false;

  /**
   * Specify whether the Checkbox is currently invalid
   */
  @property({ type: Boolean })
  invalid = false;

  /**
   * Provide the text that is displayed when the Checkbox is in an invalid state
   */
  @property({ type: String, attribute: 'invalid-text' })
  invalidText;

  /**
   * Specify a title for the node for the Checkbox
   */
  @property({ attribute: 'title' })
  title = '';

  /**
   * The value.
   */
  @property()
  value!: string;

  /**
   * Specify whether the Checkbox is in a warn state
   */
  @property({ type: Boolean })
  warn = false;

  /**
   * Provide the text that is displayed when the Checkbox is in a warn state
   */
  @property({ type: String, attribute: 'warn-text' })
  warnText = false;

  /**
   * Specify whether the underlying input should be checked by default
   */
  @property({ type: Boolean, attribute: 'default-checked' })
  defaultChecked;

  /**
   * Handles `slotchange` event.
   */
  protected _handleSlotChange({ target }: Event) {
    const hasContent = (target as HTMLSlotElement)
      .assignedNodes()
      .filter((elem) =>
        (elem as HTMLElement).matches !== undefined
          ? (elem as HTMLElement).matches(
              (this.constructor as typeof CDSCheckbox).aiLabelItem
            ) ||
            // remove slug reference in v12
            (elem as HTMLElement).matches(
              (this.constructor as typeof CDSCheckbox).slugItem
            )
          : false
      );

    this._hasAILabel = Boolean(hasContent);
    const type = (hasContent[0] as HTMLElement).getAttribute('kind');
    (hasContent[0] as HTMLElement).setAttribute(
      'size',
      type === 'inline' ? 'md' : 'mini'
    );
    this.requestUpdate();
  }

  /**
   * `true` if there is an AI Label.
   */
  protected _hasAILabel = false;

  updated() {
    const { _hasAILabel: hasAILabel } = this;
    if (hasAILabel) {
      this.setAttribute('ai-label', '');
    } else {
      this.removeAttribute('ai-label');
    }
  }
  connectedCallback() {
    super.connectedCallback();
    if (this.defaultChecked) {
      this.checked = this.defaultChecked;
    }
  }

  render() {
    const {
      checked,
      disabled,
      helperText,
      hideLabel,
      id,
      indeterminate,
      invalid,
      invalidText,
      labelText,
      name,
      readonly,
      title,
      value,
      warn,
      warnText,
      defaultChecked,
      _handleChange: handleChange,
      _handleClick: handleClick,
    } = this;

    const showWarning = !readonly && !invalid && warn;
    const showHelper = !invalid && !warn;

    const helper = helperText
      ? html` <div class="${prefix}--form__helper-text">${helperText}</div>`
      : null;

    const labelClasses = classMap({
      [`${prefix}--checkbox-label`]: true,
    });
    const labelTextClasses = classMap({
      [`${prefix}--checkbox-label-text`]: true,
      [`${prefix}--visually-hidden`]: hideLabel,
    });
    return html`
      <input
        id="${ifDefined(id)}"
        type="checkbox"
        part="input"
        class="${`${prefix}--checkbox`}"
        aria-readonly="${String(Boolean(readonly))}"
        .checked="${checked}"
        ?data-invalid="${invalid}"
        ?disabled="${disabled}"
        ?defaultChecked="${defaultChecked}"
        .indeterminate="${indeterminate}"
        name="${ifDefined(name)}"
        value="${ifDefined(value)}"
        @change="${handleChange}"
        @click="${handleClick}" />
      <label
        for="${ifDefined(id)}"
        part="label"
        class="${labelClasses}"
        title="${ifDefined(title)}">
        <span class="${labelTextClasses}"
          >${labelText ? labelText : html`<slot></slot>`}</span
        >
      </label>
      <slot name="ai-label" @slotchange="${this._handleSlotChange}"></slot>
      <slot name="decorator" @slotchange="${this._handleSlotChange}"></slot>
      <slot name="slug" @slotchange="${this._handleSlotChange}"></slot>
      <div class="${prefix}--checkbox__validation-msg">
        ${!readonly && invalid
          ? html`
              ${iconLoader(WarningFilled16, {
                class: `${prefix}--checkbox__invalid-icon`,
              })}
              <div class="${prefix}--form-requirement">${invalidText}</div>
            `
          : null}
        ${showWarning
          ? html`
              ${iconLoader(WarningAltFilled16, {
                class: `${prefix}--checkbox__invalid-icon ${prefix}--checkbox__invalid-icon--warning`,
              })}
              <div class="${prefix}--form-requirement">${warnText}</div>
            `
          : null}
      </div>
      ${showHelper ? helper : null}
    `;
  }

  /**
   * The name of the custom event fired after this changebox changes its checked state.
   */
  static get eventChange() {
    return `${prefix}-checkbox-changed`;
  }

  /**
   * A selector that will return the slug item.
   *
   * Remove in v12
   */
  static get slugItem() {
    return `${prefix}-slug`;
  }

  /**
   * A selector that will return the ai-label item.
   */
  static get aiLabelItem() {
    return `${prefix}-ai-label`;
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static styles = styles;
}

export default CDSCheckbox;

// packages/react/src/components/Checkbox/Checkbox.tsx
/**
 * Copyright IBM Corp. 2016, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React, { ReactElement, ReactNode } from 'react';
import classNames from 'classnames';
import { Text } from '../Text';
import { deprecate } from '../../prop-types/deprecate';
import { usePrefix } from '../../internal/usePrefix';
import { WarningFilled, WarningAltFilled } from '@carbon/icons-react';
import { useId } from '../../internal/useId';
import { noopFn } from '../../internal/noopFn';

type ExcludedAttributes = 'id' | 'onChange' | 'onClick' | 'type';

export interface CheckboxProps
  extends Omit<
    React.InputHTMLAttributes<HTMLInputElement>,
    ExcludedAttributes
  > {
  /**
   * Provide an `id` to uniquely identify the Checkbox input
   */
  id: string;

  /**
   * Provide a label to provide a description of the Checkbox input that you are
   * exposing to the user
   */
  labelText: NonNullable<ReactNode>;

  /**
   * **Experimental**: Provide a `decorator` component to be rendered inside the `Checkbox` component
   */
  decorator?: ReactNode;

  /**
   * Specify whether the underlying input should be checked by default
   */
  defaultChecked?: boolean;

  /**
   * Specify whether the Checkbox should be disabled
   */
  disabled?: boolean;

  /**
   * Provide text for the form group for additional help
   */
  helperText?: ReactNode;

  /**
   * Specify whether the label should be hidden, or not
   */
  hideLabel?: boolean;

  /**
   * Specify whether the Checkbox is in an indeterminate state
   */
  indeterminate?: boolean;

  /**
   * Specify whether the Checkbox is currently invalid
   */
  invalid?: boolean;

  /**
   * Provide the text that is displayed when the Checkbox is in an invalid state
   */
  invalidText?: ReactNode;

  /**
   * @deprecated please use decorator instead.
   * **Experimental**: Provide a `Slug` component to be rendered inside the `Checkbox` component
   */
  slug?: ReactNode;

  /**
   * Specify whether the Checkbox is currently invalid
   */
  warn?: boolean;

  /**
   * Provide the text that is displayed when the Checkbox is in an invalid state
   */
  warnText?: ReactNode;

  /**
   * Provide an optional handler that is called when the internal state of
   * Checkbox changes. This handler is called with event and state info.
   * `(event, { checked, id }) => void`
   */
  onChange?: (
    evt: React.ChangeEvent<HTMLInputElement>,
    data: { checked: boolean; id: string }
  ) => void;

  /**
   * Provide an optional onClick handler that is called on click
   */
  onClick?: (evt: React.MouseEvent<HTMLInputElement>) => void;
}

const Checkbox = React.forwardRef(
  (
    {
      className,
      decorator,
      helperText,
      id,
      labelText,
      onChange = noopFn,
      onClick,
      indeterminate = false,
      invalid,
      invalidText,
      hideLabel,
      readOnly,
      title = '',
      warn,
      warnText,
      slug,
      ...other
    }: CheckboxProps,
    ref
  ) => {
    const prefix = usePrefix();

    const showWarning = !readOnly && !invalid && warn;
    const showHelper = !invalid && !warn;

    const checkboxGroupInstanceId = useId();

    const helperId = !helperText
      ? undefined
      : `checkbox-helper-text-${checkboxGroupInstanceId}`;

    const helper = helperText ? (
      <div id={helperId} className={`${prefix}--form__helper-text`}>
        {helperText}
      </div>
    ) : null;

    const wrapperClasses = classNames(
      `${prefix}--form-item`,
      `${prefix}--checkbox-wrapper`,
      className,
      {
        [`${prefix}--checkbox-wrapper--readonly`]: readOnly,
        [`${prefix}--checkbox-wrapper--invalid`]: !readOnly && invalid,
        [`${prefix}--checkbox-wrapper--warning`]: showWarning,
        [`${prefix}--checkbox-wrapper--slug`]: slug,
        [`${prefix}--checkbox-wrapper--decorator`]: decorator,
      }
    );
    const innerLabelClasses = classNames(`${prefix}--checkbox-label-text`, {
      [`${prefix}--visually-hidden`]: hideLabel,
    });

    let normalizedDecorator = React.isValidElement(slug ?? decorator)
      ? (slug ?? decorator)
      : null;
    if (
      normalizedDecorator &&
      normalizedDecorator['type']?.displayName === 'AILabel'
    ) {
      const size =
        (normalizedDecorator as ReactElement).props?.['kind'] === 'inline'
          ? 'md'
          : 'mini';
      normalizedDecorator = React.cloneElement(
        normalizedDecorator as React.ReactElement<any>,
        {
          size,
        }
      );
    }

    return (
      <div className={wrapperClasses}>
        <input
          {...other}
          type="checkbox"
          data-invalid={invalid ? true : undefined}
          onChange={(evt) => {
            if (!readOnly && onChange) {
              onChange(evt, { checked: evt.target.checked, id });
            }
          }}
          className={`${prefix}--checkbox`}
          id={id}
          ref={(el) => {
            if (el) {
              el.indeterminate = indeterminate ?? false;
            }
            if (typeof ref === 'function') {
              ref(el);
            } else if (ref && 'current' in ref) {
              ref.current = el;
            }
          }}
          // readonly attribute not applicable to type="checkbox"
          // see - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
          aria-readonly={readOnly}
          onClick={(evt) => {
            if (readOnly) {
              // prevent default stops the checkbox being updated
              evt.preventDefault();
            }
            // pass onClick event on to the user even if readonly
            if (onClick) {
              onClick(evt);
            }
          }}
        />
        <label
          htmlFor={id}
          className={`${prefix}--checkbox-label`}
          title={title}>
          <Text className={innerLabelClasses}>
            {labelText}
            {slug ? (
              normalizedDecorator
            ) : decorator ? (
              <div className={`${prefix}--checkbox-wrapper-inner--decorator`}>
                {normalizedDecorator}
              </div>
            ) : (
              ''
            )}
          </Text>
        </label>
        <div className={`${prefix}--checkbox__validation-msg`}>
          {!readOnly && invalid && (
            <>
              <WarningFilled className={`${prefix}--checkbox__invalid-icon`} />
              <div className={`${prefix}--form-requirement`}>{invalidText}</div>
            </>
          )}
          {showWarning && (
            <>
              <WarningAltFilled
                className={`${prefix}--checkbox__invalid-icon ${prefix}--checkbox__invalid-icon--warning`}
              />
              <div className={`${prefix}--form-requirement`}>{warnText}</div>
            </>
          )}
        </div>
        {showHelper && helper}
      </div>
    );
  }
);

Checkbox.propTypes = {
  /**
   * Specify whether the underlying input should be checked
   */
  checked: PropTypes.bool,

  /**
   * Specify an optional className to be applied to the <label> node
   */
  className: PropTypes.string,

  /**
   * **Experimental**: Provide a decorator component to be rendered inside the `Checkbox` component
   */
  decorator: PropTypes.node,

  /**
   * Specify whether the underlying input should be checked by default
   */
  defaultChecked: PropTypes.bool,

  /**
   * Specify whether the Checkbox should be disabled
   */
  disabled: PropTypes.bool,

  /**
   * Provide text for the form group for additional help
   */
  helperText: PropTypes.node,

  /**
   * Specify whether the label should be hidden, or not
   */
  hideLabel: PropTypes.bool,

  /**
   * Provide an `id` to uniquely identify the Checkbox input
   */
  id: PropTypes.string.isRequired,

  /**
   * Specify whether the Checkbox is in an indeterminate state
   */
  indeterminate: PropTypes.bool,

  /**
   * Specify whether the Checkbox is currently invalid
   */
  invalid: PropTypes.bool,

  /**
   * Provide the text that is displayed when the Checkbox is in an invalid state
   */
  invalidText: PropTypes.node,

  /**
   * Provide a label to provide a description of the Checkbox input that you are
   * exposing to the user
   */
  labelText: PropTypes.node.isRequired,

  /**
   * Provide an optional handler that is called when the internal state of
   * Checkbox changes. This handler is called with event and state info.
   * `(event, { checked, id }) => void`
   */
  onChange: PropTypes.func,

  /**
   * Specify whether the Checkbox is read-only
   */
  readOnly: PropTypes.bool,

  /**
   * **Experimental**: Provide a `Slug` component to be rendered inside the `Checkbox` component
   */
  slug: deprecate(
    PropTypes.node,
    'The `slug` prop has been deprecated and will be removed in the next major version. Use the decorator prop instead.'
  ),

  /**
   * Specify a title for the <label> node for the Checkbox
   */
  title: PropTypes.string,

  /**
   * Specify whether the Checkbox is currently in warning state
   */
  warn: PropTypes.bool,

  /**
   * Provide the text that is displayed when the Checkbox is in warning state
   */
  warnText: PropTypes.node,
};

Checkbox.displayName = 'Checkbox';

export default Checkbox;
