// packages/react/src/components/Accordion/Accordion.Skeleton.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import cx from 'classnames';
import { ChevronRight } from '@carbon/icons-react';
import SkeletonText from '../SkeletonText';
import { usePrefix } from '@carbon/utilities-react';

export interface AccordionSkeletonProps {
  /**
   * Specify the alignment of the accordion heading
   * title and chevron.
   */
  align?: 'start' | 'end';

  /**
   * Specify an optional className to add.
   */
  className?: string;

  /**
   * Set number of items to render.
   */
  count?: number;

  /**
   * Specify whether an individual AccordionItem should
   * be flush, default is false.
   */
  isFlush?: boolean;

  /**
   * `false` to not display the first item opened.
   */
  open?: boolean;

  /**
   * Specify if the Accordion should be an ordered list,
   * default is `false`
   */
  ordered?: boolean;
}

function AccordionSkeleton({
  align = 'end',
  className,
  count = 4,
  isFlush,
  open = true,
  ordered = false,
  ...rest
}: AccordionSkeletonProps) {
  const prefix = usePrefix();
  const classes = cx(`${prefix}--accordion`, `${prefix}--skeleton`, className, {
    [`${prefix}--accordion--${align}`]: align,
    [`${prefix}--accordion--flush`]: isFlush && align !== 'start',
  });
  const numSkeletonItems = open ? count - 1 : count;
  const ListTag = ordered ? 'ol' : 'ul';
  return (
    <ListTag className={classes} {...rest}>
      {open && (
        <li
          className={`${prefix}--accordion__item ${prefix}--accordion__item--active`}>
          <span className={`${prefix}--accordion__heading`}>
            <ChevronRight className={`${prefix}--accordion__arrow`} />
            <SkeletonText className={`${prefix}--accordion__title`} />
          </span>
          <div className={`${prefix}--accordion__content`}>
            <SkeletonText width="90%" />
            <SkeletonText width="80%" />
            <SkeletonText width="95%" />
          </div>
        </li>
      )}
      {Array.from({ length: numSkeletonItems }).map((_, i) => (
        <AccordionSkeletonItem key={i} />
      ))}
    </ListTag>
  );
}

AccordionSkeleton.propTypes = {
  /**
   * Specify the alignment of the accordion heading title and chevron.
   */
  align: PropTypes.oneOf(['start', 'end']),

  /**
   * Specify an optional className to add.
   */
  className: PropTypes.string,

  /**
   * Set number of items to render
   */
  count: PropTypes.number,

  /**
   * Specify whether an individual AccordionItem should be flush, default is false
   */
  isFlush: PropTypes.bool,

  /**
   * `false` to not display the first item opened
   */
  open: PropTypes.bool,
};

function AccordionSkeletonItem() {
  const prefix = usePrefix();
  return (
    <li className={`${prefix}--accordion__item`}>
      <span className={`${prefix}--accordion__heading`}>
        <ChevronRight className={`${prefix}--accordion__arrow`} />
        <SkeletonText className={`${prefix}--accordion__title`} />
      </span>
    </li>
  );
}

export default AccordionSkeleton;
export { AccordionSkeleton };

// packages/web-components/src/components/accordion/accordion-skeleton.ts
/**
 * Copyright IBM Corp. 2019, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import { ACCORDION_ALIGNMENT } from './accordion';
import { forEach } from '../../globals/internal/collection-helpers';
import ChevronRight16 from '@carbon/icons/es/chevron--right/16.js';
import { iconLoader } from '../../globals/internal/icon-loader';
import './accordion-item-skeleton';
import '../skeleton-text/index';
import styles from './accordion.scss?lit';

import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Skeleton of code snippet.
 */
@customElement(`${prefix}-accordion-skeleton`)
class CDSAccordionSkeleton extends LitElement {
  /**
   * Specify the alignment of the accordion heading title and chevron
   */
  @property({ reflect: true })
  alignment = ACCORDION_ALIGNMENT.END;

  /**
   * Set number of items to render
   */
  @property({ type: Number, attribute: 'count' })
  count = 4;

  /**
   * Specify whether Accordion text should be flush, default is false, does not work with align="start"
   */
  @property({ type: Boolean, reflect: true })
  isFlush = false;

  /**
   * `true` if the first accordion item should be open.
   */
  @property({ type: Boolean, reflect: true })
  open = true;

  updated(changedProperties) {
    if (changedProperties.has('alignment')) {
      // Propagate `alignment` attribute to descendants until `:host-context()` gets supported in all major browsers
      forEach(
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- https://github.com/carbon-design-system/carbon/issues/20071
        this.shadowRoot!.querySelectorAll(
          (this.constructor as typeof CDSAccordionSkeleton)
            .selectorAccordionItemSkeletons
        ),
        (elem) => {
          elem.setAttribute('alignment', this.alignment);
        }
      );
    }
    if (
      changedProperties.has('isFlush') ||
      changedProperties.has('alignment')
    ) {
      // Propagate `isFlush` attribute to descendants until `:host-context()` gets supported in all major browsers
      forEach(
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- https://github.com/carbon-design-system/carbon/issues/20071
        this.shadowRoot!.querySelectorAll(
          (this.constructor as typeof CDSAccordionSkeleton)
            .selectorAccordionItemSkeletons
        ),
        (elem) => {
          if (this.isFlush && this.alignment !== 'start') {
            elem.setAttribute('isFlush', '');
          } else {
            elem.removeAttribute('isFlush');
          }
        }
      );
    }
  }

  render() {
    const classes = classMap({
      [`${prefix}--accordion__item`]: true,
      [`${prefix}--accordion__item--active`]: true,
      [`${prefix}--accordion--${this.alignment}`]: this.alignment,
      [`${prefix}--accordion--flush`]:
        this.isFlush && this.alignment !== 'start',
    });
    const numSkeletonItems = this.open ? this.count - 1 : this.count;
    return html`
      ${this.open
        ? html`
            <li class="${classes}">
              <span class="${prefix}--accordion__heading">
                ${iconLoader(ChevronRight16, {
                  class: `${prefix}--accordion__arrow`,
                  part: 'expando-icon',
                })}
                <cds-skeleton-text
                  class="${prefix}--accordion__title"></cds-skeleton-text>
              </span>
              <div class="${prefix}--accordion__content">
                <cds-skeleton-text width="90%"></cds-skeleton-text>
                <cds-skeleton-text width="80%"></cds-skeleton-text>
                <cds-skeleton-text width="95%"></cds-skeleton-text>
              </div>
            </li>
          `
        : ``}
      ${Array.from({ length: numSkeletonItems }).map(
        (_, i, arr) =>
          html`<cds-accordion-item-skeleton
            key=${i}
            ?data-last-item=${i ===
            arr.length - 1}></cds-accordion-item-skeleton>`
      )}
    `;
  }

  static get selectorAccordionItemSkeletons() {
    return `${prefix}-accordion-item-skeleton`;
  }

  static styles = styles;
}

export default CDSAccordionSkeleton;
