// packages/react/src/components/Accordion/Accordion.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import { usePrefix } from '@carbon/utilities-react';
import PropTypes from 'prop-types';
import React, { PropsWithChildren, ReactNode } from 'react';
import { AccordionProvider } from './AccordionProvider';

export interface AccordionProps {
  /**
   * Specify the alignment of the accordion heading
   * title and chevron. Defaults to `end`.
   */
  align?: 'start' | 'end';

  /**
   * Specify an optional className to be applied to
   * the container node.
   */
  className?: string;

  /**
   * Pass in the children that will be rendered within the Accordion
   */
  children?: ReactNode;

  /**
   * Specify whether an individual AccordionItem
   * should be disabled.
   */
  disabled?: boolean;

  /**
   * Specify whether Accordion text should be flush,
   * default is `false`, does not work with `align="start"`.
   */
  isFlush?: boolean;

  /**
   * Specify if the Accordion should be an ordered list,
   * default is `false`
   */
  ordered?: boolean;

  /**
   * Specify the size of the Accordion. Currently
   * supports the following: `sm`, `md`, `lg`
   */
  size?: 'sm' | 'md' | 'lg';
}

function Accordion({
  align = 'end',
  children,
  className: customClassName,
  disabled = false,
  isFlush = false,
  ordered = false,
  size,
  ...rest
}: PropsWithChildren<AccordionProps>) {
  const prefix = usePrefix();

  const className = cx(`${prefix}--accordion`, customClassName, {
    [`${prefix}--accordion--${align}`]: align,
    [`${prefix}--accordion--${size}`]: size, // TODO: V12 - Remove this class
    [`${prefix}--layout--size-${size}`]: size,
    [`${prefix}--accordion--flush`]: isFlush && align !== 'start',
  });
  const ListTag = ordered ? 'ol' : 'ul';

  return (
    <AccordionProvider disabled={disabled}>
      <ListTag className={className} {...rest}>
        {children}
      </ListTag>
    </AccordionProvider>
  );
}

Accordion.propTypes = {
  /**
   * Specify the alignment of the accordion heading title and chevron.
   */
  align: PropTypes.oneOf(['start', 'end']),

  /**
   * Pass in the children that will be rendered within the Accordion
   */
  children: PropTypes.node,

  /**
   * Specify an optional className to be applied to the container node
   */
  className: PropTypes.string,

  /**
   * Specify whether an individual AccordionItem should be disabled
   */
  disabled: PropTypes.bool,

  /**
   * Specify whether Accordion text should be flush, default is false, does not work with align="start"
   */
  isFlush: PropTypes.bool,

  /**
   * Specify if the Accordion should be an ordered list,
   * default is `false`
   */
  ordered: PropTypes.bool,

  /**
   * Specify the size of the Accordion. Currently supports the following:
   */
  size: PropTypes.oneOf(['sm', 'md', 'lg']),
};

export default Accordion;

// packages/web-components/src/components/accordion/accordion.ts
/**
 * Copyright IBM Corp. 2019, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import { forEach } from '../../globals/internal/collection-helpers';
import { ACCORDION_SIZE, ACCORDION_ALIGNMENT } from './defs';
import styles from './accordion.scss?lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

export { ACCORDION_SIZE, ACCORDION_ALIGNMENT };

/**
 * Accordion container.
 *
 * @element cds-accordion
 */
@customElement(`${prefix}-accordion`)
class CDSAccordion extends LitElement {
  /**
   * Accordion size should be sm, md, lg.
   */
  @property({ reflect: true })
  size = ACCORDION_SIZE.MEDIUM;

  /**
   * Specify the alignment of the accordion heading title and chevron
   */
  @property({ reflect: true })
  alignment = ACCORDION_ALIGNMENT.END;

  /**
   * Specify whether Accordion text should be flush, default is false, does not work with align="start"
   */
  @property({ type: Boolean, reflect: true })
  isFlush = false;

  /**
   * Disable all accordion items inside this accordion.
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'list');
    }
    super.connectedCallback();
  }

  updated(changedProperties) {
    if (changedProperties.has('size')) {
      // Propagate `size` attribute to descendants until `:host-context()` gets supported in all major browsers
      forEach(
        this.querySelectorAll(
          (this.constructor as typeof CDSAccordion).selectorAccordionItems
        ),
        (elem) => {
          elem.setAttribute('size', this.size);
        }
      );
    }
    if (changedProperties.has('alignment')) {
      // Propagate `alignment` attribute to descendants until `:host-context()` gets supported in all major browsers
      forEach(
        this.querySelectorAll(
          (this.constructor as typeof CDSAccordion).selectorAccordionItems
        ),
        (elem) => {
          elem.setAttribute('alignment', this.alignment);
        }
      );
    }
    if (
      changedProperties.has('isFlush') ||
      changedProperties.has('alignment')
    ) {
      // Propagate `isFlush` attribute to descendants until `:host-context()` gets supported in all major browsers
      forEach(
        this.querySelectorAll(
          (this.constructor as typeof CDSAccordion).selectorAccordionItems
        ),
        (elem) => {
          if (this.isFlush && this.alignment !== 'start') {
            elem.setAttribute('isFlush', '');
          } else {
            elem.removeAttribute('isFlush');
          }
        }
      );
    }

    if (changedProperties.has('disabled')) {
      forEach(
        this.querySelectorAll(
          (this.constructor as typeof CDSAccordion).selectorAccordionItems
        ),
        (elem) => {
          if (this.disabled) {
            elem.setAttribute('disabled', '');
          } else {
            elem.removeAttribute('disabled');
          }
        }
      );
    }

    // Marks the last accordion item for styling (simulates :last-child in Shadow DOM)
    const items = Array.from(
      this.querySelectorAll(
        (this.constructor as typeof CDSAccordion).selectorAccordionItems
      )
    );
    items.forEach((item) => item.removeAttribute('data-last-item'));

    const lastVisible = items
      .reverse()
      .find((item) => !(item as HTMLElement).hidden);
    lastVisible?.setAttribute('data-last-item', '');
  }

  render() {
    return html` <slot></slot> `;
  }

  static get selectorAccordionItems() {
    return `${prefix}-accordion-item`;
  }

  static styles = styles;
}

export default CDSAccordion;
